[tox]
requires =
    tox>=4.11
env_list =
    test
    format-check
    build

[testenv:test]
description = Run unit tests and output coverage report
extras =
    test
commands =
    coverage run -m pytest
    coverage report

[testenv:format-check]
description = Check code is compliant with ruff
skip_install = true
deps =
    {[testenv:format]deps}
commands =
    ruff check {posargs}
    ruff format --diff {posargs}
    pyproject-fmt pyproject.toml --check

[testenv:build]
description = Build the sdist and wheel and check their metadata
skip_install = true
deps =
    build>=1.2
    twine>=5
commands =
    python -c "import shutil; shutil.rmtree('dist', ignore_errors=True)"
    python -m build
    twine check --strict dist/{env:DIST_GLOB:*}

[testenv:format]
description = Automatically format and lint code using ruff
skip_install = true
deps =
    pyproject-fmt==2.8
    ruff==0.14.2
commands =
    ruff check --fix {posargs}
    ruff format {posargs}
    - pyproject-fmt pyproject.toml
